export default {
  title: '',
  slug: '',
  date: new Date().toISOString().slice(0, 10),
  categories: [],
  tags: [],
  tagString: '',
  abstract: null,
  authors: null,
  authorString: null,
  citation: null,
  description: null,
  doi: '',
  funding: null,
  mainfiletype: '',
  markdown: '',
  notes: null,
  noteString: null,
  project: null,
  sources: null,
  sourceString: null,
  timeperiod: null,
  timeperiodString: null,
  timeperiodType: null,
  thumbnail: null,
  variables: null,
  variableString: null,
  unit: null,
  url: null,
  apps: null,
  articles: null,
  datasets: null
}
